name: Deploy website to Keroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # git clone
      - uses: actions/checkout@v2
      # linter
      - uses: michaellw90/PHP-Lint@master
